services:
  backend:
    build: ./backend
    container_name: cyberplatform_tfg-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - Database_URL= mysql+pymysql://root:root@db:5432/usuarios_db
    networks:
      - cyberplatform_network

  db:
    image: mysql:latest
    container_name: cyberplatform_tfg-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  cyberplatform_network:
    driver: bridge